name:                Haskell-re
version:             0.1.0.0
github:              "higuoxing/Haskell-re"
license:             MIT
author:              "Xing GUO"
maintainer:          "higuoxing@gmail.com"
copyright:           "2018 Xing GUO"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Haskell-re#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  Haskell-re-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-re

tests:
  Haskell-re-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-re
